# Generated by Django 5.2.7 on 2025-10-21 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallDetailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('VOICE_OUT', 'Outgoing Voice'), ('VOICE_IN', 'Incoming Voice'), ('SMS_OUT', 'Outgoing SMS'), ('SMS_IN', 'Incoming SMS'), ('DATA', 'Data')], max_length=20)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('cost_amount', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdrs', to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'started_at'], name='cdr_calldet_custome_aae66b_idx')],
            },
        ),
    ]
