# Generated by Django 5.2.7 on 2025-10-21 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REVENUE', 'Revenue'), ('CALLS', 'Calls')], max_length=20)),
                ('period', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rank', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'period', 'period_start', 'period_end'], name='analyticsap_kind_38d40f_idx'), models.Index(fields=['customer'], name='analyticsap_custome_cbfa0b_idx')],
                'unique_together': {('kind', 'period', 'period_start', 'period_end', 'customer')},
            },
        ),
    ]
